# -*- coding: utf-8 -*-
"""Streamlit and Python Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HIHn9w2rVmSuVBXe8CCotn7N9THhvYgT

1. What is Streamlit, and how does it differ from other web frameworks?

Streamlit is an open-source Python framework for building interactive, data-driven web applications. It is designed to be easy to use, even for those with no prior experience in web development. Streamlit works by providing a simple interface for creating interactive widgets and displaying data visualizations. This makes it easy to create web applications that allow users to explore and interact with data in a variety of ways.

It differs from other web frameworks in ways such as:
* Streamlit is specifically designed for data science and machine learning applications. This means that it provides a number of features that are useful for these types of applications, such as the ability to easily display data visualizations and interact with machine learning models.

* Streamlit is very fast and lightweight.

* Streamlit is easy to use, even for those with no prior experience in web development. Streamlit works by providing a simple interface for creating interactive widgets and displaying data visualizations.

2. Explain the basic structure of a Streamlit app.

The basic structure of a Streamlit app is quite simple. Here are the key components:
1. Importing streamlit as st
2. st.title and st.write functions can be used to add titles and text
3. A lot of interactive widgets can be used to display information such as st.button, st.slider,st.header etc...
4. Data visualization is made easy with the import of libraries such as matplotlib,plotly, etc...
5. Data processing can be done by importing pandas
6. Finally we can run it by using streamlit run app.py

3. How can you add a title to your Streamlit app?

You can add a title to your Streamlit app using the st.title function
st.title("Scifor Technologies")
We can use st.header and st.subheader for heading levels and st.text to add text in that

4. What is the purpose of the st.write() function in Streamlit?

The st.write() function in streamlit is a  function that can be used to display a variety of content in a Streamlit app. It can be used to display text, dataframes, charts, images, videos and more.

5. How do you create interactive widgets in Streamlit? Provide examples.

Streamlit provides a variety of interactive widgets that allow users to interact with your app. Few of the examples are:
1. st.write() is used to add a text
st.write("Hello World")
2. st.title() is used to add a title
st.title ("this is the app title")
3. st.header is used to set header of a section
st.header("this is the header")
4. st.markdown is used to set a markdown of a section
st.markdown("this is the markdown")
5. st.subheader is used to set subheader of a section
st.subheader("this is the subheader")
6. st.caption is used to write caption
st.caption("this is the caption")
7. st.image() is used to display an image
8. st.video() is used to display a video
9. st.audio() is used to display an audio
10. st.sidebar() will make the element pinned to the left
To add a title to the sidebar, use the st.sidebar.title() function
To add text to the sidebar, use the st.sidebar.write() function
11. st.pyplot() is used to display matplotlib figures. We can display line charts, barcharts, area charts etc.
These are only a few of the examples of the interactive widgets in streamlit.
"""